name: append-to-file-every-2min

on:
  schedule:
    - cron:  "*/2 * * * *"   # every 2 minutes (UTC)
  workflow_dispatch:         # manual "Run workflow" button for instant test

jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Append to file and commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "A new word was added at $(date)" >> log.txt
          git add log.txt
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: append to log.txt"
          git push 